# Site
repository: jvet/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Dimitri Ivanenko
title: Administrateur Systèmes et Réseaux Senior. 
email: dimitri.ivanenko@gmail.com    

# Social links
#twitter_username: facespics
github_username:  jvet 
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: dimitri-ivanenko-24b33314
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: A propos de moi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  * Passioné depuis toujours par l'informatique et open source.
  * Motivé, polyvalent avec des années d'experience dans le domaine d'hébergement web et de production.
  * Efficace, flexible, dynamique, autonome, avec une grande capacité d'adaptation et un sens des resposabilités.

  ___


  |:**Nationalité:** Ukrainien |:**Location:** Aubonne (Susse)  |
  |:**Permis de conduire:** EU categories A,B |:**Langues:** **ru** (Langue maternelle), **fr** (bilingue), **en** (téchnique), **un** (bilingue) |



# Projects Section
projects_title: Projets et Missions

# Experience Section
experience_title: Expérience professionnelle

# Education Section
educaton_title: Formation 

# More Section
more_title: Intérets et Hobbies 
more_content: | # this will include new lines to allow paragraphs
  En plus d'être passionné par l'informatique et l'électronique mes hobbies sont:
   - Randonnée 
   - Voyages
   - Musées et éxpositions 
   - Concerts et Festivals 

# Footer
footer_show_references: false 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
